services:
  - type: web
    name: financial-qa-agent-system
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src:/opt/render/project/src/api:/opt/render/project/src/core:/opt/render/project/src/models
      - key: UVICORN_HOST
        value: 0.0.0.0
      - key: UVICORN_PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1"
      # Google Cloud Configuration (add these as secret environment variables in Render)
      - key: GOOGLE_CLOUD_PROJECT
        value: "xooper-450012"
      - key: GOOGLE_CLOUD_LOCATION
        value: "us-central1"
      # GOOGLE_APPLICATION_CREDENTIALS should be set as a secret in Render dashboard
      # pointing to the JSON credentials content
    disk:
      name: financial-qa-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    healthCheckPath: /api/v1/health

  # Optional: Background worker for data ingestion
  - type: worker
    name: financial-qa-ingestion-worker
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: python run_ingestion.py
    envVars:
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: PYTHONUNBUFFERED
        value: "1"
    disk:
      name: financial-qa-data
      mountPath: /opt/render/project/src/data
      sizeGB: 1
    # Run once to populate data, then can be disabled
    autoDeploy: false

databases:
  # Optional: Redis for caching (if needed)
  - name: financial-qa-cache
    plan: starter